
services:
    php83:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      container_name: php83
      volumes:
      - .:/var/www/html
      networks:
      - app-network

    webnginx:
      image: nginx:stable-alpine
      container_name: webnginx
      volumes:
        - ./public:/var/www/html/public:ro
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./docker/nginx/web.vhost:/etc/nginx/conf.d/default.conf:ro
      ports:
        - "8082:80"
      depends_on:
        - php83
      networks:
        - app-network
      restart: unless-stopped

    node:
      build: docker/node
      container_name: icad_node
      restart: unless-stopped
      volumes:
        - .:/var/www/html
      command: bash -c "yarn && yarn dev --watch"
      depends_on:
        - php83
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
    app-data:
        driver: local
